### ISSUE TITLE
Ex_7_concentration_input.py giving an error

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#172]
I tried to run Ex_7_concentration_input.py but am getting an error (using KIPET version 1.0.6). The notebook is [here](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_paresto/Ex_7_concentration_input_wk.ipynb). I would appreciate if you are able to spot what I might be doing incorrectly.

**Comment by kwmcbride** [comment]
I'm not sure if the issue is found within block 19 where there is a typo in "covariance". Could you change correct this to ensure that this is the source of the error?

**Comment by notesofdabbler** [comment]
I corrected the typo in "covariance" and it gives a different error now ([notebook link](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_paresto/Ex_7_concentration_input_wk.ipynb)). I also tried by taking out kaug so that only ipopt is used and that also give a error ([notebook link](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_paresto/Ex_7_concentration_input_wk_nokaug.ipynb)).

**Comment by kwmcbride** [comment]
The first error when using k_aug is because there is a newer version with a new output format for getting the relevant information. You can just as easily use "sipopt" here instead, if you don't have the latest version of k_aug installed.

I am still not sure what the second error is. My first concern is that Ipopt is not being called? Can you confirm this? I will try to recreate your error in a clean environment.

If it something to do with KIPET, then I may have already fixed this in the upcoming version, 1.0.7. This new version fixes a number of bugs and adds several new features as well.

**Comment by notesofdabbler** [comment]
I will wait for 1.0.7 and try this example then.

**Comment by kwmcbride** [comment]
I should have the latest version ready this week or next.

**Comment by notesofdabbler** [comment]
I just wanted to check if 1.0.7 is currently available.
