### ISSUE TITLE
non absorbing species

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#26]
A potential solution has been implemented in the branch `non_absorbing` the [file](https://github.com/dthierry/kipet/blob/non_absorbing/kipet/examples/Paper/replicate_example51a_non_absorbing.py) contains an example case study (lines 60 and 61). 

The workflow is as follows:
create *list* of strings of non-absorbing species. Pass it to the method `set_non_absorbing_species` referencing the model and the list. 
The side effects of this method call are:
- The creation of a new non_absorbing set.
- Fixing the corresponding columns of the S matrix to 0.
- Creating a constraint `C[time, fixed component] == Z[time, fixed component]`

The issues with `VarianceEstimation` were resolved for the most part although I can't verify that this strategy works out as expected.
No issues were found with `ParameterEstimation`.

The example will fail because the assertion would not be satisfied but other than that the model is constructed as expected.

**Comment by mchlshort** [comment]
Hi @dthierry ,

Running the problem and removing the assertion gives me this:

EXIT: Optimal Solution Found.
The estimated parameters are:
k2 1.0
k1 0.22813095281968615

![image](https://user-images.githubusercontent.com/36671927/39410951-5721c702-4bce-11e8-8749-b29973672cfe.png)

![image](https://user-images.githubusercontent.com/36671927/39410948-4b9b173a-4bce-11e8-996e-27eac77804b0.png)

Isn't it a bit strange that we can still see component C's absorbance profile? Any idea why this might be?

**Comment by dthierry** [comment]
Oh no. I will get back to you on this soon.

**Comment by schenkch** [comment]
It would be good to add an example for that as well. I will see how far I can get with putting one of my case studies as an example in there.

**Comment by dthierry** [comment]
I have committed the fix for the non-absorbing species. This [file](https://github.com/dthierry/kipet/blob/non_absorbing/kipet/examples/Paper/replicate_example51a_non_absorbing.py) (at the `non_absorbing` branch), provides an example on how it works (line 61-67, this example will run for a sweet long time so beware). Now the result should have a horizontal line at zero for the absorbance of `c`, as expected.
The problem is that it is much more difficult than I originally thought. `VarianceEstimation` and `ParameterEstimation` now have significant changes whenever there is indexing over the component set. It seems to work right now but I have little confidence on the *correctness* of the results. In other words I am surprised this even works.
I think an easier fix would be to put the *non-absorbing* species as part of the additional differential states, but hopefully the current *hack* will do. I have run the unit tests and it seems that everything else is still working.

**Comment by mchlshort** [comment]
Hi @dthierry so I ran your fix on a couple problems and it seems to be doing ok. I generated some data for a problem where the product 'C' in A -> B -> C does not absorb and it seems to solve quite nicely. So well done!

Just a little problem I seem to have noticed with the error messages. When something is wrong with the model, even when the problem appears to have nothing to do with whether you have correctly defined the absorbing components or not, I get the error:

`
  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 521, in __getattr__
    % (self.__class__.__name__, val))

AttributeError: 'ConcreteModel' object has no attribute 'non_absorbing'`

Do you have any idea why this could be? i.e. This error came from me putting in a different number for the finite elements for the problem...

**Comment by mchlshort** [comment]
Also, just a heads up that the reason the problem took so long to solve seems to be that the setting up of the VarianceEstimator took a really long time. You can speed this up by decreasing the size of the A_set and it still solves to a decent solution

**Comment by dthierry** [comment]
Could you attach the full traceback?

**Comment by mchlshort** [comment]
`Traceback (most recent call last):

  File "<ipython-input-39-080c012eecf4>", line 1, in <module>
    runfile('/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/Paper/noise_studies/sdae_sim_non_abs.py', wdir='/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/Paper/noise_studies')

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/Paper/noise_studies/sdae_sim_non_abs.py", line 138, in <module>
    tolerance=1e-6)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/VarianceEstimator.py", line 170, in run_opt
    self._solve_Z(solver)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/VarianceEstimator.py", line 321, in _solve_Z
    if k in self.model.non_absorbing:

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 521, in __getattr__
    % (self.__class__.__name__, val))

AttributeError: 'ConcreteModel' object has no attribute 'non_absorbing'`

**Comment by dthierry** [comment]
Ah I see , thank you for noting that. I have fixed it in the non_abs branch.

**Comment by mchlshort** [comment]
Hi @dthierry , think I found another small issue with the new code. When you include the with_d_vars option it throws the following error:

`ERROR: Rule failed when generating expression for constraint D_bar_constraint
    with index (0.025, 1.0): AttributeError: 'ConcreteModel' object has no
    attribute '_sublist_components'
ERROR: Constructing component 'D_bar_constraint' from data=None failed:
    AttributeError: 'ConcreteModel' object has no attribute
    '_sublist_components'
Traceback (most recent call last):

  File "<ipython-input-8-41ba35b53d6c>", line 1, in <module>
    runfile('/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/case51c/pyomo/estimation.py', wdir='/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/case51c/pyomo')

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/case51c/pyomo/estimation.py", line 102, in <module>
    with_d_vars=True)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/ParameterEstimator.py", line 411, in run_opt
    **kwds)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/ParameterEstimator.py", line 106, in _solve_extended_model
    rule=rule_D_bar)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 540, in __setattr__
    self.add_component(name, val)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 980, in add_component
    val.construct(data)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/constraint.py", line 793, in construct
    ndx)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/misc.py", line 57, in apply_indexed_rule
    return rule(model, *index)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/ParameterEstimator.py", line 102, in rule_D_bar
    return m.D_bar[t, l] == sum(m.C[t, k] * m.S[l, k] for k in m._sublist_components)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 521, in __getattr__
    % (self.__class__.__name__, val))

AttributeError: 'ConcreteModel' object has no attribute '_sublist_components'`

Any ideas on this?

**Comment by dthierry** [comment]
Ah, a silly one. I have the fix, I am just gonna do the unit tests again.

**Comment by dthierry** [comment]
I think this should be fixed by now on the same branch. One thing is that all of my `scaled` estimation cases appear to be failing on the tests (I think they work in reality). `michaels` estimation is failing as well for some reason.

**Comment by schenkch** [comment]
That is strange. I have a look at this and test it with the updated test script included in the chris_unittest branch as well.

**Comment by schenkch** [comment]
@dthierry : Did you run the tests for the same branch? I have the feeling the examples included in here are not the updated ones that work. I ran a few manually and with the tests so far and they fail for both.

**Comment by dthierry** [comment]
@schenkch I think you are right. `non_absorbing` is using old tests. I will update them from your branch shortly.

**Comment by schenkch** [comment]
@dthierry But I think also old examples that were not fixed yet. @mchlshort  You fixed some of them but I don't remember in which branch they are.

**Comment by mchlshort** [comment]
Think the ones I fixed are in the master branch

**Comment by mchlshort** [comment]
I know I am a bit late on this one, but are you guys getting any errors running problems with the with_d_vars option on? I get the following:

ERROR: Rule failed when generating expression for constraint D_bar_constraint
    with index (0.9, 1.0): AttributeError: 'ConcreteModel' object has no
    attribute '_sublist_components'
ERROR: Constructing component 'D_bar_constraint' from data=None failed:
    AttributeError: 'ConcreteModel' object has no attribute
    '_sublist_components'
Traceback (most recent call last):

  File "<ipython-input-2-d036e95f6da1>", line 1, in <module>
    runfile('/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/Paper/replicate_example52a.py', wdir='/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/Paper')

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/examples/Paper/replicate_example52a.py", line 119, in <module>
    with_d_vars=True)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/ParameterEstimator.py", line 411, in run_opt
    **kwds)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/ParameterEstimator.py", line 106, in _solve_extended_model
    rule=rule_D_bar)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 540, in __setattr__
    self.add_component(name, val)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 980, in add_component
    val.construct(data)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/constraint.py", line 793, in construct
    ndx)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/misc.py", line 57, in apply_indexed_rule
    return rule(model, *index)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/kipet-0.0.0-py2.7.egg/kipet/opt/ParameterEstimator.py", line 102, in rule_D_bar
    return m.D_bar[t, l] == sum(m.C[t, k] * m.S[l, k] for k in m._sublist_components)

  File "/home/shortm/anaconda2/lib/python2.7/site-packages/Pyomo-5.4.3-py2.7.egg/pyomo/core/base/block.py", line 521, in __getattr__
    % (self.__class__.__name__, val))

AttributeError: 'ConcreteModel' object has no attribute '_sublist_components'

Also, @dthierry , is it possible for you to please turn off the generation of whatevs.nl, whatevs.row, whatevs.col, _reconcilied.col, _reconcilied.row, and iterations.log when you next merge. Otherwise, I think we can close this issue when these have been implemented and tested.

**Comment by dthierry** [comment]
Hi @mchlshort , I think that was the same issue as the previous fix?. Did you update your local repository?
Also, I will turn of the `whatevs` file generation right away.
