### ISSUE TITLE
Errors with fixing parameters and running sipopt

### ISSUE THREAD

**Issue by schenkch** [salvadorgarciamunoz/kipet#48]
There are some issues with fixing parameters and running parameter estimation with sipopt. 
I tried to find the cause for that and it looks like Kipet still counts the fixed parameter as a variable for which sensitivities are tried to be calculated which of course causes a problem.  
So we have to make sure that self.model.P in the ParameterEstimator file just includes the non-fixed ones.

**Comment by mchlshort** [comment]
Where did you try and fix the parameters? When I fix parameters at the TemplateBuilder using this:

    builder.add_parameter('k1',bounds=(0.0,5.0))
    builder.add_parameter('k2', 0.2)

It solves for k1, giving confidence intervals, and does not give confidence intervals for k2. Granted, the value for k2 needs to be given quite precisely or else sIpopt fails. This will be an issue for estimability analysis later, so we need to come up with a decent strategy for how to deal with this.

**Comment by schenkch** [comment]
That is what I did as well. I just tried it with a fresh clone and it still does not work. I tried it for the values you set it to as well but it still gives the same error. Did you run it with the kipet-master or another version?

**Comment by mchlshort** [comment]
I am running with kipet-master. do you have the 'with_d_vars = True' option set? I realize that I might have added this in (i.e. not part of the master version of this example). My solver options are also:

    options['mu_init'] = 1e-6
    options['bound_push'] =1e-6

This is for Ex_2_estimation

**Comment by schenkch** [comment]
Yes, I have the same options. That is strange.

**Comment by schenkch** [comment]
It is not a version issue but the solution seems to be system dependent. 

If I run it with ipopt first and then fix k2 to the estimated value. The solution for the other parameter basically has to be in the middle of its bounds and not too far off. Such that no bounds or relaxing the bounds makes it worse. This is due to the fact that the parameters are initialized with 1 in the TemplateBuilder. This is basically the same as for the states. That is a problem and I think that should be changed.

**Comment by mchlshort** [comment]
Hi @schenkch, would you like to re-try this with the new TemplateBuilder in the fe_factory_interface branch? Just interested to see the results on that.

**Comment by schenkch** [comment]
Hi @mchlshort, I just tried that but I still get the same issues. Or did you mean that I should try that in connection with an fe by fe initialization?

**Comment by mchlshort** [comment]
Thanks for giving it a try @schenkch, I think I was hoping that the parameters would be initialized to a different value, but I think I found the issue. Basically, during the apply_discretization() the initializations that are set during the TemplateBuilder's create_pyomo_model() function are overwritten. I will try and implement a fix and will let you know.

**Comment by mchlshort** [comment]
ok, I am now sure that it is not the initializations that are causing the issues. I did a very detailed check, line-by-line and the issue is definitely related to the calculation of the reduced hessian in sIpopt. At this stage I haven't figured out why, but the error seems to relate in some way to memory allocation and seems to be an issue mostly in C, not really Python.

**Comment by dthierry** [comment]
A .nl file of this problem (that reproduces the failure running ipopt_sens nl.nl) might allow me to give you more insight on sipopt. As for kipet, the .py of the example and the name active branch might help me connect the dots.

**Comment by mchlshort** [comment]
Hi @dthierry, ok, I have a very jumbled local branch where I have been messing around with it trying to fix the issue, but I think that the example I will attach has the issue on the master or other branches. Just to try and clarify a few things before you see the nl files. Obviously you can get this problem to work with the right bounds and fixed parameter. The issue does not occur during the ipopt solve in sIpopt, but only when the reduced Hessian is calculated, so I am not too sure if the nl files include this or not?

Anyways, I have attached the errors in the terminal as well as an example file that should be able to reproduce the error and one that works as well as the nl files.

Thanks for having a look!
Let me know if everything works for you or not.

[errors and example.zip](https://github.com/salvadorgarciamunoz/kipet/files/2210254/errors.and.example.zip)

**Comment by dthierry** [comment]
Hi Mike,
I tried both files that you send me, and they do not have any issues. Also I tried the nl file and it seems to be from a different run.
Judging from the output, I think is a bug related to the problem that you are trying to compute the RH on. It is probably not well defined. It is my understanding that you wouldn't attempt to compute the RH on a variable that is fixed; bc that is not defined in the computation of the RH (numerically); but that I don't know for sure what you're attempting to do. Anyhow, are you able to reproduce the errors with the files that you've sent me?.

**Comment by mchlshort** [comment]
Hi @dthierry I checked the files again and I do still get the errors. I am using the fix_fe_factory branch now and I still get the errors. The nl files, you are right, are not correct and this is because I couldn't figure out how to get them for the file with the error. try: solve except ApplicationError: and RuntimeError both seem to not work as they are not defined, so not sure how to get them to output for a failed run. I only realised now that the nl files were not working. I have attached what I checked and a slightly clearer version of the outputs. It is really strange that you are unable to reproduce the errors... What version of sIpopt are you using?
[files.zip](https://github.com/salvadorgarciamunoz/kipet/files/2214272/files.zip)

**Comment by mchlshort** [comment]
Finally I have managed to get the correct nl files. Interestingly enough, when trying to implement confidence intervals for the C-only estimation I managed to get the same error, even though neither of the parameters were fixed. So the cause of the error is even more mysterious to me now.

Attached is the nl file and the example code that generates it.

[finally correct nl.zip](https://github.com/salvadorgarciamunoz/kipet/files/2237112/finally.correct.nl.zip)

**Comment by dthierry** [comment]
Hey Mike, good news; I've discover why the infamous double call to ipopt "fix" works. It is actually not fixing anything, it just so happens that the first call deletes the suffixes for the red_hess. Then, the second call (now with `ipopt_sens`) doesn't compute the red_hess because there are no suffixes, and then the confidence intervals are non-existent. 
If I redefine the suffixes each time after solving; the sipopt bug happens again.

**Comment by mchlshort** [comment]
Aaaah, that makes sense. Well done! Doesn't quite illuminate us on where the sIpopt issue is coming from though.

Just to let you know, I decreased the problem size and that does actually seem to help. The error disappears and solutions are generated. What we could potentially do then is to create an additional argument in the ParameterEstimation that can be used in a similar way to the A_set in VarianceEstimator, however we can make it do either reducing the time periods or reducing the lambdas (or both?). This will allow the user to decide whether they would like to reduce the problem or not based on whether sIpopt works or not. 

While not quite fixing the problem, it could be a workaround. We will need to see if reducing the problem size works for all cases where these sIpopt issues are found though in order to see whether that really is the cause of the issue or not.

**Comment by dthierry** [comment]
I have tried the branch [fix_sipopt](https://github.com/salvadorgarciamunoz/kipet/tree/fix_sipopt) to solve the fixing parameters' issues with sIpopt. 
Hopefully, this will be enough.

**Comment by mchlshort** [comment]
Everything seems to be working well with these fixes. Well done for finding and dealing with the bug. Thanks a lot! @schenkch , if you can give it a try on one of your problems to confirm this your side then we should be good to merge and close this issue.

**Comment by schenkch** [comment]
Well done, @dthierry ! I just tested it for a few cases that did not work before. Everything seems to be working well now. So, I think we should be good to merge and close the issue.

**Comment by mchlshort** [comment]
Fantastic. It is done
